accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('mypage/',views.Mypage.as_view(),  name='mypage'),
    path('follow/<int:pk>', views.followShop, name='follow'),
    path('kanrisha/', views.CountMember.as_view(), name='kanrisha'),
    path('member_delete/<int:pk>', views.memberDelete.as_view(), name='MemberDelete'),
    path('member_update/<int:pk>',views.memberUpdate.as_view(), name='MemberUpdate'),
    path('kiyaku/', views.kiyaku.as_view(), name='kiyaku'),
    path('password_change/', views.passwordChange.as_view(), name='password_change'),
    path('password_change_done/', views.passwordChangeDone.as_view(), name='password_change_done'),
    path('signup_and_login',views.SignupAndLoginView.as_view(), name='signup_and_login'),
]

credit/urls.py
from django.urls import path
from . import views
from django.conf import settings            
from django.conf.urls.static import static  

app_name = "credit"

urlpatterns = [
    path('credit/', views.ProductTopPageView.as_view(), name='product_top_page'),
    path("create-checkout-session/<pk>/", views.CreateCheckoutSessionView.as_view(), name="create-checkout-session"),    # 個別商品決済画面
    path("webhook/", views.stripe_webhook, name="webhook"),  
    path('subscription/', views.SubscriptionCancel.as_view(), name='subscription_cancel'),
    path('cardinfo/<int:kokyaku_pk>/', views.CardinfoUpdateAndDelete.as_view(), name='cardinfo_update_delete'),
    path('update-card/', views.update_card, name='update_card'), # endpoint用
]

# メディア表示
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nagoyameshi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('shops/', include("shops.urls")),
    path('schedule/', include("schedule.urls")),
    path('credit/', include("credit.urls")),
    path('review/', include("review.urls")),
     # accounts以外のアプリはPATH関数の第1引数にアプリ名を書く
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views
from django.conf import settings            
from django.conf.urls.static import static  

app_name = "review"

urlpatterns = [
    path('review_update/<int:pk>', views.reviewUpdate.as_view(), name='UpdateReview'),
    path('review_display/<int:pk>', views.reviewDisplay.as_view(), name='DisplayReview'),
    path('review_delete', views.reviewDelete.as_view(), name='DeleteReview'),
]

# メディア表示
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shops"

urlpatterns = [
    path('shop_create/',views.ShopCreateView.as_view(), name='shop_create'),
    path('shop_detail/<int:pk>/', views.ShopDetailView3.as_view(), name='shop_detail'),
    path('result_success/', views.ResultSuccessView.as_view(), name='success'),
    path('result_failure/', views.ResultFailureView.as_view(), name='failure'),
    path('shop_update_form/<int:pk>',views.ShopUpdateView.as_view(), name='shop_update'),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import (BaseUserManager,
                                        AbstractBaseUser,
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import make_password
from shops.models import Shop

# Create your models here.

class UserManager(BaseUserManager):
    def _create_user(self, email, account_id, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, account_id=account_id, **extra_fields)
        user.set_password(make_password(password))
        user.save(using=self._db)

        return user

    def create_user(self, email, account_id, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )

    def create_superuser(self, email, account_id, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )


class User(AbstractBaseUser, PermissionsMixin):

    account_id = models.CharField(
        verbose_name=_("アカウント名"),
        unique=True,
        max_length=10,
    )
    email = models.EmailField(
        verbose_name=_("メールアドレス"),
        unique=True,
    )
    first_name = models.CharField(
        verbose_name=_("姓"),
        max_length=150,
        null=True,
        blank=True,
    )
    last_name = models.CharField(
        verbose_name=_("名"),
        max_length=150,
        null=True,
        blank=True,
    )
    rank_is_free = models.BooleanField(
        verbose_name=_("会員ランク"),
        help_text="無料会員ならTrue、デフォルトは無料会員",
        default=True,
    )
    birth_date = models.DateField(
        verbose_name=_("誕生日"),
        blank=True,
        null=True,
    )
    is_superuser = models.BooleanField(
        verbose_name=_("管理者かどうか"),
        default=False,
    )
    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
    )
    created_at = models.DateTimeField(
        verbose_name=_("作成日"),
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        verbose_name=_("更新日"),
        auto_now=True,
    )
    favorite_shop = models.ManyToManyField(
        Shop,
        verbose_name=_('お気に入り店舗'),
        blank=True,
        related_name='related_favorite_shop',
    )
    shop_review_comment = models.ForeignKey(
        Shop,
        verbose_name=_('レビューコメント'),
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='related_shop_review_comment',
    )

    objects = UserManager()

    USERNAME_FIELD = 'account_id' # ログイン時、ユーザー名の代わりにaccount_idを使用
    REQUIRED_FIELDS = ['email']  # スーパーユーザー作成時にemailも設定する

    def __str__(self):
        return self.account_id
    def yoyaku_id(self):
        return Yoyaku_ID.objects.filter(account=self.account_id)

class Yoyaku_ID(models.Model):
    account = models.ForeignKey(User,verbose_name='ユーザー',on_delete=models.CASCADE,null=True,blank=True,related_name='related_user')
    yoyaku_Id = models.TextField(verbose_name='予約ID',max_length=255,null=True)
    def __str__(self) -> str:
        return self.yoyaku_Id

class Kiyaku(models.Model):
    kiyakuName = models.CharField(verbose_name='規約名称', unique=True, max_length=10)
    kiyakuContent = models.TextField(verbose_name='規約内容',blank=True)
    updated_at = models.DateTimeField(verbose_name=_('最終更新時間'), auto_now=True)
    lastUpdater = models.ForeignKey(User,verbose_name='最終更新者',on_delete=models.CASCADE,blank=True,related_name='last_update_user')
    def __str__(self) -> str:
        return self.kiyakuName

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DeleteView
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
)
from django.urls import reverse_lazy, reverse
from .forms import SignUpForm, LoginForm,MyPasswordChangeForm
from dotenv import load_dotenv
from .models import User,Kiyaku
from shops.models import Shop, ShopTag # Shopモデルをインポート
from schedule.models import Schedule
from review.models import Review
from django.db.models import Avg, Q
from django.contrib import messages
from django.views import View

import os
import requests
import calendar
import datetime
import json
from django.http import JsonResponse
from django.core.serializers.json import DjangoJSONEncoder

# Create your views here.

#staticのファイル更新日時を取得
#各Views.pyでcontext['style_???_date'] = get_modified_date('css/???.css')
#各TemplateのStaticのリンクの末尾に{% if style_css_date %}?={{ style_css_date }}{% endif %}を追記
from django.templatetags.static import static
from django.conf import settings
from datetime import datetime, timedelta, timezone
import os
def get_modified_date(filepath):
    try:
        static_file_path = static(filepath)
        base_dir = settings.BASE_DIR
        static_file_url = os.path.join(base_dir, *static_file_path.split("/"))

        modified_serial_time = os.path.getmtime(static_file_url)
        modified_date = datetime.fromtimestamp(modified_serial_time).strftime("%Y%m%d%H%M%S")

        return modified_date

    except:
        return ''
#ここまで    

class IndexView(ListView): 
    # ホームビュー
    template_name = 'index.html'
    model = User
    def get_context_data(self, **kwargs):
        load_dotenv(os.path.join(os.path.dirname(__file__), 'nagoyameshi/.env'))
        context = super().get_context_data(**kwargs)
        context['views_APIkey'] = os.getenv('env_APIkey')
        context['shoptag_list'] = ShopTag.objects.all()
        context['style_css_date'] = get_modified_date('css/top2.css')
        context['style_js_date'] = get_modified_date('js/map.js')
        return context
    #名前検索
    def get_queryset(self):
        query = self.request.GET.get('query')
        selectTag = self.request.GET.get('selectTag')
        
        #デフォルトは表示なし
        if not self.request.GET:
            shop_list = None
            return shop_list
        #検索条件に合わせて表示
        if selectTag != 'all':
            if query:
                if selectTag: #タグと名前検索に入力あり
                    shop_list = Shop.objects.filter(ShopTag=selectTag,shopName__icontains=query)
                else : #名前検索のみ
                    shop_list = Shop.objects.filter(shopName__icontains=query)
            else: #タグのみ
                shop_list = Shop.objects.filter(ShopTag=selectTag)
        else:
            if query: #タグが全店舗で名前検索に入力あり
                shop_list = Shop.objects.filter(shopName__icontains=query)
            else: #タグが全検索のとき
                shop_list = Shop.objects.all()
        return shop_list

class SignupAndLoginView(View):
    def get(self, request, *args, **kwargs):
        signup_form = SignUpForm()
        login_form = LoginForm()
        context = {
            'signup_form': signup_form,
            'login_form': login_form,
            'style_css_date': get_modified_date('css/signup_and_login.css'),
        }
        return render(request, 'accounts/signup_and_login.html', context)

    def post(self, request, *args, **kwargs):
        signup_form = SignUpForm(request.POST)
        login_form = LoginForm(request, data=request.POST)

        if 'signup' in request.POST:
            # サインアップフォームの送信処理
            if signup_form.is_valid():
                user = signup_form.save()
                account_id = signup_form.cleaned_data.get('account_id')
                password = signup_form.cleaned_data.get('password1')
                user = authenticate(account_id=account_id, password=password)
                if user is not None:
                    login(request, user)
                return redirect('accounts:index')

        elif 'login' in request.POST:
            # ログインフォームの送信処理
            if login_form.is_valid():
                login(request, login_form.get_user())
                return redirect('accounts:index')

        # どちらかが無効の場合、再度フォームを表示
        return render(request, 'accounts/signup_and_login.html', {
            'signup_form': signup_form,
            'login_form': login_form,
        })

class LogoutView(BaseLogoutView):
    # ログアウトビュー
    success_url_= reverse_lazy('index') 


class Mypage(TemplateView):
    model = User
    template_name = 'accounts/mypage.html'
    def get(self, request, *args, **kwargs):
        d = datetime.today().date()
        t = datetime.today().time()
        # 親クラスのコンテキストを取得
        context = super().get_context_data(**kwargs)
        context['style_css_date'] = get_modified_date('css/mypage.css')
        context['style_js_date'] = get_modified_date('js/mypage.js')
        # ユーザー情報をコンテキストに追加
        context['user'] = self.request.user
        # お気に入り店舗情報
        favorite_shops = request.user.favorite_shop.all()
        context['favorite_shop_json'] = json.dumps(list(favorite_shops.values('shopName')))

        # 予約（今日以降）とレビューのリストをコンテキストに追加
        user = User.objects.get(pk=self.request.user.pk) 
        schedule_queryset = Schedule.objects.filter(account=user, startDate__gte=d)  
        # 今日日付で現在時刻より前の予約はキャンセル不可なので表示しない
        schedule_queryset=schedule_queryset.exclude(startDate=d,startHour__lte=t) 
        schedule_list = list(schedule_queryset.values('shop_name', 'startDate', 'startHour', 'name', 'numbers', 'pk'))
        review_queryset = Review.objects.filter(reviewUserName=request.user)
        review_list = []

        # 各スケジュールにキャンセルURLを追加
        for schedule in schedule_list:
            schedule['cancel_url'] = reverse('schedule:delete', args=[schedule['pk']])

        # 各レビューに編集URLを追加
        for review in review_queryset:
            review_list.append({
                'reviewShopName': review.reviewShopName.shopName,
                'reviewStar': review.reviewStar,
                'reviewComment': review.reviewComment,
                'cancel_url_review': reverse('review:UpdateReview', args=[review.pk])   
            })

        context['schedule_list'] = schedule_list
        context['review_list_json'] = json.dumps(review_list, cls=DjangoJSONEncoder)
        context['schedule_list_json'] = json.dumps(schedule_list, cls=DjangoJSONEncoder)
        return render(request, self.template_name, context)
        
    def post(self, request, *args, **kwargs):
        user = User.objects.get(account_id = request.user)
        # お気に入り店舗を削除
        if 'delete-favorite-shop' in request.POST:
            delete_shop_name = request.POST.get('delete-shop')
            delete_shop_id = Shop.objects.get(shopName=delete_shop_name).id
            user.favorite_shop.remove(delete_shop_id)
            user.save()
            return redirect('accounts:mypage')
        elif 'withdrawal-membership' in request.POST:
            # ユーザー自身による退会処理
            user.delete()
            return redirect('accounts:index')
        
def followShop(request, pk):
    f_shop = get_object_or_404(Shop, pk=pk)
    request.user.favorite_shop.add(f_shop)
    return redirect('accounts:mypage')

class CountMember(TemplateView):    
    template_name = 'accounts/kanrisha.html'
    def get(self, request, *args, **kwargs):
        context = {
            'style_css_date': get_modified_date('css/kanrisha.css'),
            'dateUser': '-',
            'allShop': Shop.objects.count(),
            'Shops': Shop.objects.all(),
            'countTag': ShopTag.objects.count(),
            'allTag': ShopTag.objects.all(),
        }
        return render(request, self.template_name, context)
    def post(self, request, *args, **kwargs):
        model = User
        context = super().get_context_data(**kwargs)
        context = {
            'style_css_date': get_modified_date('css/kanrisha.css'),
            'dateUser': '-',
            'allShop': Shop.objects.count(),
            'Shops': Shop.objects.all(),
            'countTag': ShopTag.objects.count(),
            'allTag': ShopTag.objects.all(),
        }
        if 'numberSearch' in request.POST:
            #入力された年月日を受け取りmodelを検索する
            inputYear = request.POST.get('inputYear')
            inputMonth = request.POST.get('inputMonth')
            inputDate = request.POST.get('inputDate')
            inputSubscription = request.POST.get('subscription')
            if inputSubscription == 'True':
                resultSubscription = '無料会員'
            else:
                resultSubscription = '有料会員'
            #年単位/月単位/日単位の判定
            #年の入力判定
            if inputYear == '':
                #全期間
                if inputSubscription == 'all':
                    context['errMsg'] = '全期間の全会員で検索'
                    context['dateUser'] = User.objects.count() 
                    return render(request, self.template_name, context)
                else:
                    context['errMsg'] = f'全期間の{resultSubscription}で検索'
                    context['dateUser'] = User.objects.filter(rank_is_free=inputSubscription).count() 
                    return render(request, self.template_name, context)
            else:
                #年OK
                resultYear = inputYear
                #月の入力判定
                if inputMonth == 'all':
                    #入力された年の1月1日から12月31日まで
                    startRange = f"{resultYear}-01-01"
                    endRange = f"{resultYear}-12-31"
                    if inputSubscription == 'all':
                        context['errMsg'] = f"{resultYear}年の1年間に登録された会員数"

templates/accounts/kanrisha.html
{% extends 'base.html' %}
{% load static %}
{% block title %}管理用画面{% endblock %}

{% block content %}


<body>
    <div class="kanrisha">
        <!--会員数検索-->
        <div class="memSearch">
            <h3>会員検索</h3>
            <p>入力された値の期間内で会員数を検索します。（年だけの入力の場合は1年間の検索結果を表示）</p>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="memberSearchTable">
                <span id="inputYear"></span>
                <span>年</span>
                <select size="1" name="inputMonth" id="inputMonth"></select>
                <span>月</span>
                <select size="1" name="inputDate" id="inputDate"></select>
                <span>日</span>
                <input type="radio" name="subscription" value="all" checked>全ての会員
                <input type="radio" name="subscription" value="True">無料会員のみ
                <input type="radio" name="subscription" value="False">有料会員のみ
                <input type="submit" name="numberSearch" value="検索">
            </form>
            <p>{{ errMsg }}：結果は{{ dateUser }}件です。</p>

            <!--会員検索-->
            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" name="memberSearchContext" size="40" placeholder="会員の名前かメールアドレスを入力（一部OK）">
                <input type="submit" name="memberSearch" value="検索">
            </form>

            {% if errMsg1 %}
                <p>{{ errMsg1 }}</p>
            {% endif %}

            <p>会員のレビューの閲覧編集</p>
            {% if searchResult %}
                <ul>
                    {% for user in searchResult %}
                        <li>
                            <p>ID: {{ user.account_id }}</p>
                            <p>メールアドレス: {{ user.email }}</p>
                            <p>氏名: {{ user.first_name }} {{ user.last_name }}</p>
                            <a href="{% url 'review:DisplayReview' pk=user.pk %}" >{{ user.account_id }}のレビューの確認と削除</a> 
                            <a href="{% url 'accounts:MemberDelete' pk=user.pk %}">{{ user.account_id }}の削除</a>
                            <a href="{% url 'accounts:MemberUpdate' pk=user.pk %}">{{ user.account_id }}の編集</a>

                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>該当するユーザーが見つかりませんでした。</p>
            {% endif %}
        </div>
        </div>

        <div class="shSearch">
            <h3>店舗情報の編集と追加</h3>
            <a class="addShop" href="{% url 'shops:shop_create' %}">新規店舗登録</a>

            <form action="" method="POST">
                {% csrf_token %}
                <select id="shopSelect">
                    {% for i in Shops %}
                    <option value="{{ i.pk }}">{{ i.shopName }}</option>
                    {% endfor %}
                </select>
                <input type="button" value="店舗情報の編集" onClick="editShop()">
            </form>

            <p>店舗数集計：{{ allShop }}</p>
        </div>
        <div class="tag-Edit">
            <h3>店舗カテゴリの検索/追加/編集/削除</h3>
            <div class="tagCount">
                <p>現在の登録カテゴリ数：{{ countTag }}</p>
                <form action="" method="POST">
                {% csrf_token %}
                    <input type="text" name="addTagContext" placeholder="新しいカテゴリを追加" size="20" required>
                    <button type="submit" name="tagAdd">カテゴリ追加</button>
                </form>
            </div>
            <div class="all-category">
                <p>現在の登録カテゴリ一覧</p>
                <form action="" method="POST">
                {% csrf_token %}
                {% for i in allTag %}
                <li>
                    {{ i.tag }}
                    <input type="hidden" name="targetTagPK" value="{{ i.pk }}">
                    <input type="text" name="targetTagContext" placeholder="新しいカテゴリ名を入力" size="20">
                    <button type="submit" name="tagEdit">カテゴリ編集</button>
                    <button type="submit" name="tagDelete">カテゴリ削除</button>
                </li>
                {% endfor %}
                </form>
                {% if sucMsg %}
                <p class="success-message">{{ sucMsg }}</p>
                {% endif %}
            </div>
            <br>
            <div class="tag-search-result">
                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="text" name="tagSearchContext" size="25" placeholder="カテゴリ名を入力（一部OK）" required>
                    <button type="submit" name="tagSearch">カテゴリ検索</button>
                </form>
            
                <p>{{ errMsg2 }}</p>
                {% if resultTag %}
                    {% for i in resultTag %}
                    <li>{{ i.tag }}</li>
                    {% endfor %}
                {% else %}
                <p>検索語句に一致するカテゴリは見つかりませんでした。</p>
                {% endif %}
            </div>
        </div>
    </div>


<!--店舗情報編集用-->
<script>
    function editShop() {
        var selectedShop = document.getElementById('shopSelect').value;  // 選択されたshopのpkを取得
        var url = "{% url 'shops:shop_update' pk=0 %}".replace("0", selectedShop);  // pk=0を選択された値に置き換える
        location.href = url;  // リダイレクト
    }
</script>

</body>
<script src="{% static 'js/kanrisha.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/kanrisha.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">
{% endblock %}

templates/accounts/kiyaku.html
{% extends 'base.html' %}
{% load static %}
{% block title %}規約画面{% endblock %}

{% block content %}


<body>
    <div id="kiyaku">
        <!-- 一般ユーザー閲覧領域 -->
        <h3>{{ original_kiyaku.kiyakuName }}</h3>
        
        <div class="kiyaku-content">
            {{ original_kiyaku.kiyakuContent | linebreaksbr }}
        </div>
    
        <p class="update-info">
            最終更新日：{{ original_kiyaku.updated_at }} 最終更新者：{{ original_kiyaku.lastUpdater }}
        </p>  
    </div>
    
    {% if user.get_username == 'nagoya_rai' %}
    <div class="admin-form-wrapper">
        <label for="btn">規約を編集するにはここをクリックしてください。</label>
        <input type="checkbox" id="btn">
        <div class="kiyaku-edit">
            <!--管理者用テキスト編集フォーム-->
            <form action="" method="POST">
                {% csrf_token %}
                <textarea type="text" rows="10" cols="50" name="inputKiyaku">{{ original_kiyaku.kiyakuContent }}</textarea>
                <p class="notice-message">編集内容を確認してから編集完了ボタンを押してください。</p>
                <input type="hidden" name="updater" value="{{ user.get_username }}">
                <button type="submit">編集完了</button>
                </form>
            {{ msg }}
        </div>
    </div>
    {% endif %}
</body>

<link rel="stylesheet" href="{% static 'css/kiyaku2.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">
<script src="{% static 'js/kiyaku.js' %}"></script>
{% endblock %}

templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}マイページ画面{% endblock %}

{% block content %}
<head>
    <meta name="csrf-token" content="{{ csrf_token }}">
</head>

<script src="{% static 'js/mypage.js' %}{% if style_js_date %}?={{ style_js_date }}{% endif %}"></script> 

<body>
    <div class="mypage">
        <div class="left-bar">
            <!--会員情報変更、予約履歴、レビュー履歴、ログアウト、退会のリンク-->
            <a id="infoUpdate" href="#">会員情報確認</a>
            <a id="schedule-button" href="#">予約履歴</a>
            <a id="review-button" href="#">レビュー履歴</a>
            <a id="favorite-button" href="#">お気に入り店舗</a>
            <a id="rank-button" href="#">有料会員登録または解約</a>
            <a id="cardinfo-button" href="#">クレジットカード情報の編集と削除</a>
            <a id="logout-button" href="#">ログアウト</a>
            <a id="withdrawal-button" href="#">退会</a>
        </div>
        <div class="mContent" id="contentArea">
            <!--left-barの選択結果を表示-->
            <p>左のサイドバーから表示したいメニューを選択してください。</p>
                        
        </div>
        <!--ランク変更とパスワード変更を追加する-->
        <div id="user-info"
            data-first-name="{{ user.first_name }}"
            data-last-name="{{ user.last_name }}"
            data-email="{{ user.email }}"
            data-account-id="{{ user.account_id }}"
            data-rank="{% if user.rank_is_free %}無料会員{% else %}有料会員{% endif %}"
            data-url1="{% url 'accounts:MemberUpdate' pk=user.pk %}"
            data-url2="{% url 'accounts:password_change' %}">
        </div>

        <div id="logout-info"
            data-yes="{% url 'accounts:logout' %}"
        ></div>

        <div id="schedule-info"
            data-schedule='{{ schedule_list_json|safe }}'
        ></div>

        <div id="review-info"
            data-review='{{ review_list_json|safe }}'
            data-rank='{{ user.rank_is_free|safe }}'
        ></div>

        <div id="favorite-info"
            data-favorite='{{ favorite_shop_json|safe }}'
        ></div>

        <div id="withdrawal-info"
            data-withdrawal="{{ user.get_username }}"
        ></div>

        <div id="rank-info"
            data-rank="{% url 'credit:product_top_page' %}"
            data-subscription="{% url 'credit:subscription_cancel' %}"
        ></div>

        <div id="cardinfo-info"
            data-cardinfo="{% url 'credit:cardinfo_update_delete' kokyaku_pk=user.pk %}"
        ></div>
    </div>
</body>
<link rel="stylesheet" href="{% static 'css/mypage.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">
{% endblock %}

templates/accounts/user_update_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ユーザー情報編集画面{% endblock %}

{% block content %}


<body>
    <!--編集時だけアカウントが切り替わる-->
    <div class="mt-3">
        <form method="post" enctype="multipart/form-data" class="updateform">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <!-- アカウントID -->
            <label for="id_account_id">アカウント名</label>
            {{ form.account_id }}
            {{ form.account_id.errors }}
            <br>
            
            <!-- メールアドレス -->
            <label for="id_email">メールアドレス</label>
            {{ form.email }}
            {{ form.email.errors }}
            <br>

            <!-- 名 -->
            <label for="id_first_name">名</label>
            {{ form.first_name }}
            {{ form.first_name.errors }}
            <br>

            <!-- 姓 -->
            <label for="id_last_name">姓</label>
            {{ form.last_name }}
            {{ form.last_name.errors }}
            <br>

            <!-- 生年月日 -->
            <label for="id_birth_date">生年月日</label>
            {{ form.birth_date }}
            {{ form.birth_date.errors }}
            <br>
            <button type="submit" class="btn btn-primary">情報を更新する</button>
        </form>
    </div>
</body>

<link rel="stylesheet" href="{% static 'css/member_update.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">


{% endblock %}