accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('mypage/',views.Mypage.as_view(),  name='mypage'),
    path('follow/<int:pk>', views.followShop, name='follow'),
    path('kanrisha/', views.CountMember.as_view(), name='kanrisha'),
    path('member_delete/<int:pk>', views.memberDelete.as_view(), name='MemberDelete'),
    path('member_update/<int:pk>',views.memberUpdate.as_view(), name='MemberUpdate'),
    path('kiyaku/', views.kiyaku.as_view(), name='kiyaku'),
    path('password_change/', views.passwordChange.as_view(), name='password_change'),
    path('password_change_done/', views.passwordChangeDone.as_view(), name='password_change_done'),
    path('signup_and_login',views.SignupAndLoginView.as_view(), name='signup_and_login'),
]

nagoyameshi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('shops/', include("shops.urls")),
    path('schedule/', include("schedule.urls")),
    path('credit/', include("credit.urls")),
    path('review/', include("review.urls")),
     # accounts以外のアプリはPATH関数の第1引数にアプリ名を書く
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shops"

urlpatterns = [
    path('shop_create/',views.ShopCreateView.as_view(), name='shop_create'),
    path('shop_detail/<int:pk>/', views.ShopDetailView3.as_view(), name='shop_detail'),
    path('result_success/', views.ResultSuccessView.as_view(), name='success'),
    path('result_failure/', views.ResultFailureView.as_view(), name='failure'),
    path('shop_update_form/<int:pk>',views.ShopUpdateView.as_view(), name='shop_update'),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect
#from review.models import Review



# Create your models here.

class ShopTag(models.Model):
    tag = models.CharField(max_length=200)  
    def __str__(self):
        return self.tag

class Shop(models.Model): 
    day = (
        ('7', '定休日無し'),
        ('1', '月曜日'),
        ('2', '火曜日'),
        ('3', '水曜日'),
        ('4', '木曜日'),
        ('5', '金曜日'),
        ('6', '土曜日'),
        ('0', '日曜日')
    )
    ShopTag = models.ManyToManyField(ShopTag, blank=True,verbose_name='カテゴリ') #店舗種別タグ
    shopName = models.CharField(max_length=20, verbose_name='店名') #店名
    phoneNumber = models.CharField(max_length=15, blank=True, null=True, verbose_name='電話番号') #電話番号（ハイフン無し）
    address = models.TextField(blank=True, null=True, verbose_name='住所') #住所
    addressLat = models.FloatField(blank=True, null=True, verbose_name='住所緯度') #緯度
    addressLng = models.FloatField(blank=True, null=True, verbose_name='住所経度') #経度
    startHour1 = models.TimeField(blank=True, null=True, verbose_name='昼営業開始時間') #営業開始時間
    endHour1 = models.TimeField(blank=True, null=True, verbose_name='昼営業終了時間') #営業終了時間
    startHour2 = models.TimeField(blank=True, null=True, verbose_name='夜営業開始時間') #営業開始時間
    endHour2 = models.TimeField(blank=True, null=True, verbose_name='夜営業終了時間') #営業終了時間
    image = models.ImageField(blank=True, null=True, verbose_name='店外観写真') #写真
    introduction = models.TextField(blank=True, null=True, verbose_name='店舗紹介文') #紹介文
    created = models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時') #作成日
    modified = models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時') #更新日
    regularHoliday = models.CharField(max_length=3, choices=day, blank=True, verbose_name='定休日（無入力で定休日無し）') # 定休日
    review = models.ManyToManyField('review.Review', blank=True, verbose_name='店舗レビュー')
    image_binary = models.BinaryField(verbose_name='本番環境用設定', blank=True, null=True) #画像データをバイナリで保存


    # 昼と夜で分割営業している店の営業時間を設定出来ない
    def __str__(self):
        return self.shopName
    def get_absolute_url(self):
        #return reverse('shops:shop_create')
        return reverse('shops:shop_detail',args=[str(self.pk)])

class RegularHoliday(models.Model):
    day = models.CharField(max_length=3, choices=[
        ('Mon', '月曜日'),
        ('Tue', '火曜日'),
        ('Wed', '水曜日'),
        ('Thu', '木曜日'),
        ('Fri', '金曜日'),
        ('Sat', '土曜日'),
        ('Sun', '日曜日')
    ])

    def __str__(self):
        return self.get_day_display()

shops/forms.py
from django import forms
from .models import Shop

class createForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = (
            'ShopTag',
            'shopName',
            'phoneNumber',
            'address',
            'addressLat',
            'addressLng',
            'startHour1',
            'endHour1',
            'startHour2',
            'endHour2',
            'image',
            'introduction',
            'regularHoliday'
        )
    def __init__(self, *args, **kwargs):
        # 任意のplaceholderテキスト
        super(createForm, self).__init__(*args, **kwargs)
        self.fields['phoneNumber'].widget.attrs.update({
            'placeholder': 'ハイフン不要'  
        })
        self.fields['address'].widget.attrs.update({
            'placeholder': '郵便番号と住所を入力'  
        })
        self.fields['addressLat'].widget.attrs.update({
            'placeholder': '住所の緯度を入力'  
        })
        self.fields['addressLng'].widget.attrs.update({
            'placeholder': '住所の経度を入力'  
        })
        self.fields['startHour1'].widget.attrs.update({
            'placeholder': 'HH:MM:SS'  
        })
        self.fields['endHour1'].widget.attrs.update({
            'placeholder': 'HH:MM:SS'  
        })
        self.fields['startHour2'].widget.attrs.update({
            'placeholder': 'HH:MM:SS'  
        })
        self.fields['endHour2'].widget.attrs.update({
            'placeholder': 'HH:MM:SS'  
        })
        self.fields['introduction'].widget.attrs.update({
            'placeholder': '店舗の紹介文を入力'  
        })
    

shops/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.views.generic import  TemplateView, ListView, DetailView, UpdateView
from django.views.generic.edit import  CreateView, DeletionMixin
from dotenv import load_dotenv
from django.urls import reverse_lazy
from .models import Shop, ShopTag
from schedule.models import Schedule
from accounts.models import User, Yoyaku_ID
from review.models import Review
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.templatetags.static import static
from django.conf import settings
from .forms import createForm

import requests 

load_dotenv()
# Create your views here.

#staticのファイル更新日時を取得
#各Views.pyでcontext['style_???_date'] = get_modified_date('css/???.css')
#各TemplateのStaticのリンクの末尾に{% if style_css_date %}?={{ style_css_date }}{% endif %}を追記
from django.templatetags.static import static
from django.conf import settings
from datetime import datetime, timedelta, timezone

import os
def get_modified_date(filepath):
    try:
        static_file_path = static(filepath)
        base_dir = settings.BASE_DIR
        static_file_url = os.path.join(base_dir, *static_file_path.split("/"))

        modified_serial_time = os.path.getmtime(static_file_url)
        modified_date = datetime.fromtimestamp(modified_serial_time).strftime("%Y%m%d%H%M%S")

        return modified_date

    except:
        return ''
#ここまで    

class TopView(TemplateView):
    template_name = 'base.html' 
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        context['style_css_date'] = get_modified_date('css/base2.css')
        context['shop1'] = Shop.objects.get(pk=1)
        return context
        # template_name変数で表示したいHTMLを名称指定する


class ShopCreateView(CreateView):
    model = Shop
    #fields = '__all__'
    form_class = createForm
    template_name = 'shops/shop_create.html'    
    success_url_= reverse_lazy('shops:shop_create') 
    success_message = '新規店舗追加成功！'
    def form_valid(self, form):
        Shop = form.save(commit=False)
        # 画像がフォームに含まれているかチェック
        if form.cleaned_data['image']:
            image_file = form.cleaned_data['image']
            # 画像データをバイナリデータに変換して保存
            bData = image_file.read()
            Shop.image_binary = memoryview(bData) 
        Shop.save()
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['style_css_date'] = get_modified_date('css/create.css')
        return context


    
class ShopDetailView3(DetailView):
    model = Shop
    template_name = 'shops/shop_detail_second.html'
    context_object_name = 'shop_detail'
    schedule_data = Schedule.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        td = datetime.today()
        days0 = td.strftime('%Y-%m-%d')
        days1b = td + timedelta(days=1)
        days1 = days1b.strftime('%Y-%m-%d')
        days2b = td + timedelta(days=2)
        days2 = days2b.strftime('%Y-%m-%d')
        context['days'] = {
            'days0': days0,
            'days1': days1,
            'days2': days2,
        }
        context['review_list'] = Review.objects.all()
        context['style_js_date'] = get_modified_date('js/shop_detail.js')
        context['style_css_date'] = get_modified_date('css/shop_detail.css')
        target_shop = Shop.objects.get(pk=self.kwargs['pk'])
        if os.getenv('DJANGO_ENV') == 'development': #開発環境の場合
            iFlag = 'image'
        elif os.getenv('DJANGO_ENV') == 'production': #本番環境の場合
            iFlag = 'binary'
        iFlag = 'binary'
        context['iFlag'] = iFlag
        print(iFlag)
        return context
    
    def post(self, request, *args, **kwargs):
        td = datetime.today()

        #受け取るもの
        favorite_shop_name = request.POST.get('favorite_shop_name')
        

        #お気に入り店舗の登録
        if favorite_shop_name is not None:
            user = User.objects.get(account_id=request.POST.get('favorite_shop_user'))
            user_favorite_shop = Shop.objects.get(shopName=favorite_shop_name)
            user.favorite_shop.add(user_favorite_shop)
            user.save()
            return redirect('accounts:mypage')
        
        #コメントの登録
        if 'review-create' in request.POST: 
            shopReview_star = request.POST.get('review-star')
            shopReview_comment = request.POST.get('review-comment')
            user = User.objects.get(account_id=request.POST.get('review-user'))
            user_review_shop = Shop.objects.get(shopName=request.POST.get('review-shop'))

            #Reviewオブジェクトの新規作成
            review = Review()  # Reviewのインスタンスを作成
            review.reviewShopName = user_review_shop
            review.reviewUserName = user
            review.reviewStar = shopReview_star
            review.reviewComment = shopReview_comment
            review.save()  # オブジェクトを保存
            return redirect('shops:success')  
        elif 'yoyaku' in request.POST:
            print('yoyaku')
            yoyaku_Date = request.POST.get('yoyaku_form1') #予約日
            yoyaku_Hour = request.POST.get('yoyaku_form2') #予約時
            yoyaku_Memb = int(request.POST.get('yoyaku_form3')) #予約人数
            yoyaku_User = User.objects.get(account_id=request.POST.get('yoyaku_form4')) #予約者名
            yoyaku_Shop = Shop.objects.get(shopName=request.POST.get('yoyaku_form5')) #予約店名   

            #Scheduleオブジェクトを新規作成
            schedule = Schedule()
            schedule.startDate = yoyaku_Date 
            schedule.startHour = yoyaku_Hour
            schedule.name = f"{yoyaku_User.first_name}　{yoyaku_User.last_name}"
            schedule.shop_name = yoyaku_Shop.shopName
            schedule.account = yoyaku_User
            schedule.numbers = yoyaku_Memb
            schedule.save()

            #予約完了メッセージを送る
            context = {'suc':'予約が完了しました。詳細はマイページからご確認ください。'}
            return render(request, 'shops/result_success.html', context)             

class ResultSuccessView(TemplateView):
    template_name = 'shops/result_success.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['style_css_date'] = get_modified_date('css/success.css')
        return context

class ResultFailureView(TemplateView):
    template_name = 'shops/result_failure.html'

class ShopUpdateView(UpdateView,DeletionMixin):
    model = Shop
    fields = (
        'ShopTag', 
        'shopName', 
        'phoneNumber', 
        'address', 
        'addressLat', 
        'addressLng', 
        'startHour1',
        'endHour1',
        'startHour2',
        'endHour2',
        'image',
        'introduction',
        'regularHoliday',
        )
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('accounts:kanrisha')
    def form_valid(self, form):
        Shop = form.save(commit=False)
        # 画像がフォームに含まれているかチェック
        if form.cleaned_data['image']:
            image_file = form.cleaned_data['image']
            # 画像データをバイナリデータに変換して保存
            bData = image_file.read()
            Shop.image_binary = memoryview(bData)
        Shop.save()
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['style_css_date'] = get_modified_date('css/shop_update.css')
        return context

class YoyakuCheck(TemplateView):
    #'shop_detail'から営業時間を引っ張る
    def post(self, request, *args, **kwargs):
        if 'yoyaku' in request.POST: #submitにname="yoyaku"を入れる
            model = Shop
            template_name = 'shops/shop_detail_second.html'
            yoyaku_start_time = request.POST.get('yoyaku_start_time')
            use_time = request.POST.get('use_time')
            object_pk = request.POST.get('object_pk')
            yoyaku_shop_name = request.POST.get('shop_name')
            yoyaku_user = request.POST.get('yoyaku_user')
            yoyaku_day_check = request.POST.get('yoyaku_day')
            yoyaku_number = request.POST.get('yoyaku_number')

templates/shops/result_failure.html
{% extends 'base.html' %}
{% block title %}管理者画面{% endblock %}
{% load static %}
{% block content %}
<!-- 失敗画面を表示する -->
<div class="failure">
    <p>{{ err }}</p>
    <p>処理に失敗しました。直前の処理をやり直してください。</p>
</div>

<link rel="stylesheet" href="{% static 'css/failure.css' %}">

{% endblock %}

templates/shops/result_success.html
{% extends 'base.html' %}
{% block title %}管理者画面{% endblock %}
{% load static %}
{% block content %}
<!-- 成功画面を表示する -->
<div class="success">
    <P>{{ suc }}</P>
    <p>処理に成功しました！</p>
</div>

<link rel="stylesheet" href="{% static 'css/success.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">

{% endblock %}

templates/shops/shop_create.html
{% extends 'base.html' %}
{% block title %}管理者画面{% endblock %}
{% load static %}
{% block content %}
    <!-- 管理者だけがログイン出来るようにする -->
<div class="shop-create">    
    <div class="mt-3">
        <h3>店舗新規追加</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="form-group">
                <label for="id_shopTag">店舗カテゴリ</label>
                {{ form.ShopTag }}
                </div>

                <div class="form-group">
                <label for="id_shopName">店舗名</label>
                {{ form.shopName }}
                </div>

                <div class="form-group">
                <label for="id_phoneNumber">電話番号</label>
                {{ form.phoneNumber }}
                </div>

                <div class="form-group">
                <label for="id_address">住所</label>
                {{ form.address }}
                </div>

                <div class="form-group">
                <label for="id_addressLat">住所緯度</label>
                {{ form.addressLat }}
                </div>

                <div class="form-group">
                <label for="id_addressLng">住所経度</label>
                {{ form.addressLng }}
                </div>

                <div class="form-group">
                <label for="id_startHour1">昼営業開始時間</label>
                {{ form.startHour1 }}
                </div>

                <div class="form-group">
                <label for="id_endHour1">昼営業終了時間</label>
                {{ form.endHour1 }}
                </div>

                <div class="form-group">
                <label for="id_startHour2">夜営業開始時間</label>
                {{ form.startHour2 }}
                </div>

                <div class="form-group">
                <label for="id_endHour2">夜営業終了時間</label>
                {{ form.endHour2 }}
                </div>

                <div class="form-group">
                <label for="id_regularHoliday">定休日</label>
                {{ form.regularHoliday }}
                </div>

                <div class="form-group">
                <label for="id_image">店舗外観画像</label>
                {{ form.image }}
                </div>

                <div class="form-group">
                <label for="id_introduction">店舗紹介文</label>
                {{ form.introduction }}
                </div>
            <button type="submit" class="btn btn-primary">新規店舗追加</button>
        </form>
    </div>
</div>
    <link rel="stylesheet" href="{% static 'css/create.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">

{% endblock %}

templates/shops/shop_detail_second.html
{% extends 'base.html' %}
{% block title %}店舗詳細画面{% endblock %}
{% load static %}
{% load custom_filters %}
{% block content %}
<div class="shousai">
  <h2 class="tenmei">{{ shop_detail.shopName }}</h2>
  <div class="worktime">
    <p  id="worktimeLunch"
      wtl_start = "{{ shop_detail.startHour1 }}"
      wtl_end = "{{ shop_detail.endHour1 }}"
      >昼営業時間：{{ shop_detail.startHour1 }}　～　{{ shop_detail.endHour1 }}
    </p>
    <p id="worktimeDinner"
      wtd_start = "{{ shop_detail.startHour2 }}"
      wtd_end  = "{{ shop_detail.endHour2 }}"
      >夜営業時間：{{ shop_detail.startHour2 }}　～　{{ shop_detail.endHour2 }}
    </p>
    <p id="regularHoliday" rgh="{{ shop_detail.regularHoliday }}">{{ shop_detail.regularHoliday }}</p>
  </div>

  <div class="main-content">
    <div class="shop-image">
      {% if iFlag == image %}
        <img src="{{ shop_detail.image.url }}" alt="{{ shop_detail.image.url }}">     
      {% else %}
        <img src="data:image/png;base64,{{ shop_detail.image_binary|b64encode }}" alt="店舗外観画像">
      {% endif %}
    </div>
    <div class="main-content2">
      {% if user.is_authenticated %} 
        {% if user.rank_is_free %}
          <p>予約機能は有料会員限定の機能です。</p>
          <br>
          <p>レビュー投稿機能は有料会員限定の機能です</p>
          <br>
          <p>お気に入り登録は有料会員限定の機能です。</p>
        {% else %}  
          <div class="input-yoyaku">
            <!-- 営業開始時間以内で予約開始時間を入力してもらう -->
            <p>予約日と予約開始時間と人数を入力してください。</p>
            <form action="" method="POST">
                {% csrf_token %}
                <select id="yoyaku_form1" name="yoyaku_form1" required></select>
                <select id="yoyaku_form2" name="yoyaku_form2" required></select>
                <select id="yoyaku_form3" name="yoyaku_form3" required>
                  <option value="1" selected>1人</option>
                  <option value="2">2人</option>
                  <option value="3">3人</option>
                  <option value="4">4人</option>
                  <option value="5">5人</option>
                  <option value="6">6人</option>
                  <option value="7">7人</option>
                  <option value="8">8人</option>
                  <option value="9">9人</option>
                  <option value="10">10人</option>
                </select>
                <input type="hidden" name="yoyaku_form4" value="{{ user.get_username }}">
                <input type="hidden" name="yoyaku_form5" value="{{ shop_detail.shopName }}">
                <button type="submit" name="yoyaku">予約</button>
            </form>
          </div>

          <div class="input-comment">
            <p>コメントを入力してからレビュー投稿ボタンを押してください。</p>
            <form action="" method="POST">
              {% csrf_token %}
              <select name="review-star" required>
                <option value="1">★</option>
                <option value="2">★★</option>
                <option value="3" selected>★★★</option>
                <option value="4">★★★★</option>
                <option value="5">★★★★★</option>
              </select>
              <textarea type="text" rows="3" cols="30" name="review-comment" placeholder="コメントを入力してください。" required></textarea>
              <input type="hidden" name="review-user" value="{{ user.get_username }}">
              <input type="hidden" name="review-shop" value="{{ shop_detail.shopName }}">
              <button type="submit" name="review-create">レビュー投稿</button>
            </form>
          </div>
          <div class="okiniiri">
            <form action="" method="post">
              <input type="hidden" name="favorite_shop_name" value="{{ shop_detail.shopName }}">
              <input type="hidden" name="favorite_shop_user" value="{{ user.get_username }}">
              <button type="submit" name="button">このお店をお気に入りに追加</button>
              {% csrf_token %}
            </form>
          </div>
        {% endif %}
      {% else %}
        <div class="input-signup">
          <a href="{% url 'accounts:signup_and_login' %}" class="btn btn-primary">コメントの投稿やお気に入り登録するには会員登録してください。</a>
        </div>
      {% endif %}
    </div>
  </div>

  <h5>直近のコメント</h5>
  <div class="latest-comment">
  <!-- この店に関する直近コメントの表示 -->
  
    <!-- review_listのreviewShopNameは外部キーなので大元のshopNameまで遡らないと一致しない -->
    <!-- reversedで新しい順に表示 -->
    <ul>
        {% for rev in review_list reversed %}
        {% if shop_detail.shopName == rev.reviewShopName.shopName %}
        <li>
          {{ rev.reviewUserName }}
          {% if rev.reviewStar == "1" %}
            ★
          {% elif rev.reviewStar == "2" %}
            ★★
          {% elif rev.reviewStar == "3" %}
            ★★★
          {% elif rev.reviewStar == "4" %}
            ★★★★
          {% elif rev.reviewStar == "5" %}
            ★★★★★
          {% endif %}
          {{ rev.reviewComment }} {{ rev.reviewUpdated }}
        </li>
        {% endif %}
        {% endfor %}
      </ul>
  </div>

  
</div>

<script src="{% static 'js/shop_detail.js' %}{% if style_js_date %}?={{ style_js_date }}{% endif %}"></script>
<link rel="stylesheet" href="{% static 'css/shop_detail.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">

{% endblock %}

templates/shops/shop_update_form.html
{% extends 'base.html' %}
{% block title %}店舗編集画面{% endblock %}
{% load static %}
{% block content %}
    <!-- 管理者だけがログイン出来るようにする -->
    <div class="shop-update">
        <div class="mt-3">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                
                <div class="form-group">
                <label for="id_shopTag">店舗カテゴリ</label>
                {{ form.ShopTag }}
                </div>

                <div class="form-group">
                <label for="id_shopName">店舗名</label>
                {{ form.shopName }}
                </div>

                <div class="form-group">
                <label for="id_phoneNumber">電話番号</label>
                {{ form.phoneNumber }}
                </div>

                <div class="form-group">
                <label for="id_address">住所</label>
                {{ form.address }}
                </div>

                <div class="form-group">
                <label for="id_addressLat">住所緯度</label>
                {{ form.addressLat }}
                </div>

                <div class="form-group">
                <label for="id_addressLng">住所経度</label>
                {{ form.addressLng }}
                </div>

                <div class="form-group">
                <label for="id_startHour1">昼営業開始時間</label>
                {{ form.startHour1 }}
                </div>

                <div class="form-group">
                <label for="id_endHour1">昼営業終了時間</label>
                {{ form.endHour1 }}
                </div>

                <div class="form-group">
                <label for="id_startHour2">夜営業開始時間</label>
                {{ form.startHour2 }}
                </div>

                <div class="form-group">
                <label for="id_endHour2">夜営業終了時間</label>
                {{ form.endHour2 }}
                </div>

                <div class="form-group">
                <label for="id_regularHoliday">定休日</label>
                {{ form.regularHoliday }}
                </div>

                <div class="form-group">
                <label for="id_image">店舗外観画像</label>
                {{ form.image }}
                </div>

                <div class="form-group">
                <label for="id_introduction">店舗紹介文</label>
                {{ form.introduction }}
                </div>

                <button type="submit" class="btn btn-primary">店舗情報更新</button>
            </form>
        </div>
    </div>
    <link rel="stylesheet" href="{% static 'css/shop_update.css' %}">

{% endblock %}