credit/urls.py
from django.urls import path
from . import views
from django.conf import settings            
from django.conf.urls.static import static  

app_name = "credit"

urlpatterns = [
    path('credit/', views.ProductTopPageView.as_view(), name='product_top_page'),
    path("create-checkout-session/<pk>/", views.CreateCheckoutSessionView.as_view(), name="create-checkout-session"),    # 個別商品決済画面
    path("webhook/", views.stripe_webhook, name="webhook"),  
    path('subscription/', views.SubscriptionCancel.as_view(), name='subscription_cancel'),
    path('cardinfo/<int:kokyaku_pk>/', views.CardinfoUpdateAndDelete.as_view(), name='cardinfo_update_delete'),
    path('update-card/', views.update_card, name='update_card'), # endpoint用
]

# メディア表示
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nagoyameshi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('shops/', include("shops.urls")),
    path('schedule/', include("schedule.urls")),
    path('credit/', include("credit.urls")),
    path('review/', include("review.urls")),
     # accounts以外のアプリはPATH関数の第1引数にアプリ名を書く
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shops"

urlpatterns = [
    path('shop_create/',views.ShopCreateView.as_view(), name='shop_create'),
    path('shop_detail/<int:pk>/', views.ShopDetailView3.as_view(), name='shop_detail'),
    path('result_success/', views.ResultSuccessView.as_view(), name='success'),
    path('result_failure/', views.ResultFailureView.as_view(), name='failure'),
    path('shop_update_form/<int:pk>',views.ShopUpdateView.as_view(), name='shop_update'),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit/models.py
from django.db import models
from accounts.models import User

# Create your models here.

class Subscription(models.Model):
    # 商品名
    name = models.CharField(max_length=100)
    # 商品概要
    description = models.CharField(max_length=255, blank=True, null=True)
    # 商品ID（★stripeの商品IDを値に用いる）
    stripe_product_id = models.CharField(max_length=100)
    # 商品写真登録用のファイル
    file = models.FileField(upload_to="product_files/", blank=True, null=True)
    # 商品詳細ページのリンク
    url  = models.URLField()

    # admin画面で商品名表示
    def __str__(self):
        return self.name

class SubscriptionPrice(models.Model):
    # 外部キーで商品マスタを紐付け
    product = models.ForeignKey(Subscription, related_name='Prices', on_delete=models.CASCADE)
    # 価格ID（★stripeの価格IDを値に用いる）
    stripe_price_id = models.CharField(max_length=100)
    # 価格
    price = models.IntegerField(default=0)
    
    # Django画面に表示する価格
    def get_display_price(self):
        return self.price

# トランザクションマスタ
class Transaction(models.Model):
    # 購入日
    date   = models.CharField(max_length=100)
    # 購入者
    customer_name = models.CharField(max_length=100)
    # 購入者のメールアドレス 購入者名はクレジットカードの名義なのでUserとは一致しない可能性あり
    email  = models.CharField(max_length=255)
    product_name = models.CharField(max_length=100)
    # 支払い金額
    product_amount = models.IntegerField()
    user_connection = models.OneToOneField(
        User,
        verbose_name='Userオブジェクトとの紐づき用',
        on_delete=models.PROTECT, # Userが解約しないで退会するのを防止する
        blank=True,
        null=True,
    )
    customer_id = models.CharField(max_length=255, verbose_name='customer_id', blank=True, null=True)

    # admin画面で商品名表示
    def __str__(self):
        return self.date + '_' + self.product_name  + '_' + self.customer_name

credit/views.py
from django.shortcuts import render
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.views.generic import TemplateView, UpdateView
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from .models import Subscription, SubscriptionPrice
from .models import Transaction 
from accounts.models import User
from django.shortcuts import render, get_object_or_404

import json
import stripe
import os

# Create your views here.
from django.templatetags.static import static
from django.conf import settings
from datetime import datetime, timedelta, timezone
import os
def get_modified_date(filepath):
    try:
        static_file_path = static(filepath)
        base_dir = settings.BASE_DIR
        static_file_url = os.path.join(base_dir, *static_file_path.split("/"))

        modified_serial_time = os.path.getmtime(static_file_url)
        modified_date = datetime.fromtimestamp(modified_serial_time).strftime("%Y%m%d%H%M%S")

        return modified_date

    except:
        return ''

import datetime 

# stripeのAPIキーを渡す
stripe_APIKey = settings.STRIPE_PUBLIC_KEY

# STRIPEのシークレットキー
stripe.api_key = settings.STRIPE_SECRET_KEY

# WEBHOOKのシークレットキー
endpoint_secret = settings.STRIPE_WEBHOOK_SECRET

if os.getenv('DJANGO_ENV') == 'development':
    YOUR_DOMAIN = 'http://127.0.0.1:8000'
else:
    YOUR_DOMAIN = 'https://nagoyameshi-rk3942-2c70d196cf95.herokuapp.com'
print(os.getenv('DJANGO_ENV'))

class ProductTopPageView(ListView):
    # 商品マスタ
    model = Subscription
    # ページリンク
    template_name = 'credit/product_top.html'
    #レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "product_list"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['style_css_date'] = get_modified_date('css/product_top.css')
        return context


# 決済画面
class CreateCheckoutSessionView(View):    
    def post(self, request, *args, **kwargs):
        # 二重でサブスクリプションに契約することを防止
        if Transaction.objects.filter(user_connection=self.request.user):
            context = {'err': 'あなたは既にサブスクリプションを契約しています。'}
            return render(request, 'shops/result_failure.html', context)

        # 商品マスタ呼出
        product = Subscription.objects.get(id=self.kwargs["pk"])
        price   = SubscriptionPrice.objects.get(product=product)

        # ドメイン 検証と本番を分ける
        
        # 決済用セッション
        checkout_session = stripe.checkout.Session.create(
            # 決済方法
            payment_method_types=['card'],
            # 決済詳細
            line_items=[
                {
                    'price': price.stripe_price_id,       # 価格IDを指定
                    'quantity': 1,                        # 数量
                },
            ],
            # POSTリクエスト時にメタデータ取得
            metadata = {
                        "product_id":product.id,
                       },
            mode='subscription',                               # 決済手段（一括）
            customer_email = request.user.email,               # メールアドレスはログインしたユーザーのを固定
            success_url=YOUR_DOMAIN + '/shops/result_success/',        # 決済成功時のリダイレクト先
            cancel_url=YOUR_DOMAIN + '/shops/result_failure/',          # 決済キャンセル時のリダイレクト先
        )
        return redirect(checkout_session.url)
    
# イベントハンドラ
@csrf_exempt
def stripe_webhook(request):
    print('phase1')
    print(request.headers)
    # サーバーのイベントログからの出力ステートメント
    #payload = request.body
    payload = request.body.decode('utf-8')
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None
    try:
        event = stripe.Webhook.construct_event(
            payload, 
            sig_header, 
            endpoint_secret
            )
        print('phase2')
    except ValueError as e:
        # 有効でないpayload
        print('pattern1')
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # 有効でない署名
        print('pattern2')
        return HttpResponse(status=400)

    # checkout.session.completedイベント検知
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        # イベント情報取得
        customer_name  = session["customer_details"]["name"]     # 顧客名
        customer_email = session["customer_details"]["email"]    # 顧客メール
        product_id     = session["metadata"]["product_id"]       # 購入商品ID
        product        = Subscription.objects.get(id=product_id)      # 購入商品情報
        product_name   = product.name                            # 購入した商品名
        amount         = session["amount_total"]                 # 購入金額（手数料抜き）
        customer_id    = session["customer"]                     # customer_id
        # DBに結果を保存 
        print('SaveTransactionStart')
        transaction, created = SaveTransaction(product_name, customer_name, customer_email, amount, customer_id)
        print('SaveTransactionComplete')

        # 結果確認
        print(session)

        # Userの情報を更新
        User.objects.filter(email=customer_email).update(rank_is_free=False)
        print('rank変更完了')

        # user_connection情報を更新
        user_instance = User.objects.filter(email=customer_email).first()
        transaction.user_connection = user_instance
        transaction.save()
        print('紐づけ完了')

    return HttpResponse(status=200)


# 顧客の商品購入履歴を保存
def SaveTransaction(product_name, customer_name, customer_email, amount, customer_id):
    # DB保存
    saveData = Transaction.objects.get_or_create(
                        product_name   =  product_name,
                        date           = datetime.datetime.now(),
                        customer_name  = customer_name,
                        email          = customer_email,
                        product_amount = amount,
                        customer_id = customer_id
                        )
    return saveData

# 新規追加
class SubscriptionCancel(View):
    def get(self, request, *args, **kwargs):
        context = {'style_css_date': get_modified_date('css/subscription.css')}
        return render(request, 'credit/subscription.html', context)
    # サブスクリプションの解除だけでクレジットカード情報はstripeに残る
    def post(self, request, *args, **kwargs):
        kokyaku_pk = request.POST.get('kokyaku-pk') # リクエストしてきたユーザーのPKを取得
        kokyaku = get_object_or_404(User, pk=kokyaku_pk)
        transactions = Transaction.objects.filter(user_connection=kokyaku)

        if transactions.exists(): 
            targetTransaction = Transaction.objects.filter(user_connection=kokyaku)
            kokyaku.rank_is_free = True # 会員ランクを変更
            kokyaku.save()
            # トランザクションごとに処理
            for transaction in transactions:
                try:
                    # 顧客IDに関連するサブスクリプションを取得
                    subscriptions = stripe.Subscription.list(customer=transaction.customer_id)

                    for subscription in subscriptions.auto_paging_iter():
                        # サブスクリプションIDを取得して削除
                        stripe.Subscription.delete(subscription.id)

                except stripe.error.StripeError as e:
                    # Stripeのエラーを処理
                    print(f"Stripe error: {e}")

            # トランザクションを削除
            transactions.delete()
            # modelから削除
            targetTransaction.delete() 

            context = {
                'suc': 'サブスクリプションを解約しました。',
                'style_css_date': get_modified_date('css/subscription.css')
            }
            return render(request, 'credit/subscription.html', context)
        else:
            kokyaku.rank_is_free = True # 会員ランクを変更
            kokyaku.save()  
            context = {
                'err': 'あなたに紐づくサブスクリプションはありませんでした。',
                'style_css_date': get_modified_date('css/subscription.css')
            }          
            return render(request, 'credit/subscription.html', context)

class CardinfoUpdateAndDelete(View):
    # 現在のカード情報を取得
    def get(self, request, *args, **kwargs):    
        
        # 顧客の PK を取得し、データベースから顧客を特定
        kokyaku_pk = kwargs.get('kokyaku_pk')
        kokyaku = get_object_or_404(User, pk=kokyaku_pk)
        transaction = Transaction.objects.filter(user_connection=kokyaku).first()

        if not transaction:
            context = {'fatal_err': 'サブスクリプション契約情報が見つかりませんでした。', 'stripe_APIKey': stripe_APIKey}
            return render(request, 'credit/cardinfo.html', context)

        customer_id = transaction.customer_id

        try:
            # 顧客に紐づくカード情報を取得
            payment_methods = stripe.PaymentMethod.list(
                customer=customer_id,
                type="card"
            )

            if not payment_methods['data']:
                context = {'err': 'カード情報が登録されていません。'}
                return render(request, 'credit/cardinfo.html', context)

            # デフォルトの支払い方法が指定されているかチェック
            default_payment_method_id = stripe.Customer.retrieve(customer_id).invoice_settings.default_payment_method
            default_payment_method = None
            for pm in payment_methods['data']:
                if pm.id == default_payment_method_id:
                    default_payment_method = pm
                    break
            if default_payment_method is None:
                default_payment_method = payment_methods['data'][0]  # 一番目のカードを表示

            # カード情報をコンテキストに格納
            context = {
                'card': {
                    'brand': default_payment_method.card.brand,  # カードブランド
                    'last4': default_payment_method.card.last4,  # カード番号の下4桁
                    'exp_month': default_payment_method.card.exp_month,  # 有効期限の月
                    'exp_year': default_payment_method.card.exp_year,    # 有効期限の年
                },
                'style_css_date': get_modified_date('css/cardinfo.css'),
                'style_js_date': get_modified_date('js/cardinfo.js'),
                'stripe_APIKey': stripe_APIKey
            }

templates/credit/cardinfo.html
{% extends 'base.html' %}
{% block title %}サブスクリプション画面{% endblock %}
{% load static %}
{% block content %}
<head>
  <script src="https://js.stripe.com/v3/"></script>
</head>

<script src="{% static 'js/cardinfo.js' %}{% if style_js_date %}?={{ style_js_date }}{% endif %}"></script> 


<body>
  {% if fatal_err %}
  <div class="fatal">
    <h1>{{ fatal_err }}</h1>
    <p>{{ user.get_username }}　さんは有料会員ではない為、クレジットカード情報がありませんでした。</p>
  </div>
  {% else %}
  <div id="card-element-container">
    <h1>クレジットカード情報の更新または削除</h1>
    <input type="hidden" id="stripe_APIKey" value="{{ stripe_APIKey }}">
    <input type="hidden" id="user-pk" value="{{ user.pk }}">
    <hr />
    <div class="cardinfo">
      <h3>現在のカード情報</h3>
      {% if card %}
      <p>カードブランド: {{ card.brand }}</p>
      <p>カード番号の下4桁: **** **** **** {{ card.last4 }}</p>
      <p>有効期限: {{ card.exp_month }}/{{ card.exp_year }}</p>
      {% else %}
      <p>カード情報が見つかりませんでした。</p>
      {% endif %}
    </div>
    <hr />
    <h3>カード情報を更新</h3>
    <small>新しいクレジットカード情報を枠内の入力し、「カード情報送信ボタン」を押してください。</small>
    <div id="card-element"> 
      <form id="payment-form" action="" method="POST">
        <div id="card-element-zone"></div>
        <button type="submit">カード情報を送信</button>
        <div id="error-message"></div>
      </form>
    </div>
    <hr />
    <div class="cardinfo-delete">
      <h3>カード情報を削除</h3>
      <small>あなたのクレジットカード情報を全て削除します。</small>
      <small>クレジットカード情報を削除すると自動的にサブスクリプションが解約されます。</small>
      <form action="" method="POST"> 
        {% csrf_token %}
        <input type="hidden" name="kokyaku-pk" value="{{ user.pk }}">
        <button type="submit" name="cardinfo-delete">現在の支払い設定のカード情報を削除</button>
      </form>
    </div>
  </div>
  {% endif %}
  <link rel="stylesheet" href="{% static 'css/cardinfo.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">
  
</body>

{% endblock %}

templates/credit/product_top.html
{% extends 'base.html' %}
{% block title %}サブスクリプション画面{% endblock %}
{% load static %}
{% block content %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>

<body>
    <section>
      <h1>サブスクリプションの購入</h1>
      <hr />
        <div class="product">
            <div class="description">
                <!-- 商品一覧をループで表示 -->
                {% for product in product_list %}
                  <h2>{{ product.name }}</h2>
                  
                  <div>{{ product.description }}</div>

                <!-- 商品に紐づく価格情報を表示 -->
                {% for price_data in product.Prices.all %}
                  <h4>価格：¥{{ price_data.get_display_price }}</h4>
                  <form action="{% url 'credit:create-checkout-session' product.id  %}" method="POST">
                  {% csrf_token %}
                  <button type="submit">購入画面に進む</button>
                  </form>
                  <p>※ボタンを押してから決済ページが表示されるまで時間が掛かります。しばらくお待ちください。※</p>
                {% endfor %}
                {% endfor %}
            </div>
        </div>       
    </section>
    <link rel="stylesheet" href="{% static 'css/product_top.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">

</body>
{% endblock %}

templates/credit/subscription.html
{% extends 'base.html' %}
{% block title %}サブスクリプション画面{% endblock %}
{% load static %}
{% block content %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>

<body>
    <section>
      <h1>サブスクリプションの解約</h1>
      <hr />
        <div class="subscription">
          <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="kokyaku-pk" value="{{ user.pk }}">
            <button type="submit">サブスクリプションを解約する</button>
          </form>
        </div>
        <div class="result-info">
          <!--太字と色付け-->
          {% if suc %}
          <p>{{ suc }}</p>
          {% elif err %}
          <p>{{ err }}</p>
          {% endif %}
        </div>       
    </section>
    <link rel="stylesheet" href="{% static 'css/subscription.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">

</body>
{% endblock %}