accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('mypage/',views.Mypage.as_view(),  name='mypage'),
    path('follow/<int:pk>', views.followShop, name='follow'),
    path('kanrisha/', views.CountMember.as_view(), name='kanrisha'),
    path('member_delete/<int:pk>', views.memberDelete.as_view(), name='MemberDelete'),
    path('member_update/<int:pk>',views.memberUpdate.as_view(), name='MemberUpdate'),
    path('kiyaku/', views.kiyaku.as_view(), name='kiyaku'),
    path('password_change/', views.passwordChange.as_view(), name='password_change'),
    path('password_change_done/', views.passwordChangeDone.as_view(), name='password_change_done'),
    path('signup_and_login',views.SignupAndLoginView.as_view(), name='signup_and_login'),
]

nagoyameshi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('shops/', include("shops.urls")),
    path('schedule/', include("schedule.urls")),
    path('credit/', include("credit.urls")),
    path('review/', include("review.urls")),
     # accounts以外のアプリはPATH関数の第1引数にアプリ名を書く
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shops"

urlpatterns = [
    path('shop_create/',views.ShopCreateView.as_view(), name='shop_create'),
    path('shop_detail/<int:pk>/', views.ShopDetailView3.as_view(), name='shop_detail'),
    path('result_success/', views.ResultSuccessView.as_view(), name='success'),
    path('result_failure/', views.ResultFailureView.as_view(), name='failure'),
    path('shop_update_form/<int:pk>',views.ShopUpdateView.as_view(), name='shop_update'),   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    
    <nav>
        <!--タイトルと規約と会員登録を上部に表示-->
        <div class="left-nav">
            <a id="title" href="{% url 'accounts:index' %}">NAGOYAMESHI</a>
            <a id="kiyakux" href="{% url 'accounts:kiyaku' %}">規約</a>
            {% if user.is_superuser %}
            <a href="{% url 'accounts:kanrisha' %}">管理者用ページ</a>
            {% endif %}   
        </div>
        <div class="right-nav">
            {% if user.is_authenticated %}
            <a id="logout" href="{% url 'accounts:logout' %}">ログアウト</a>
            <a id="signup" href="{% url 'accounts:mypage' %}">マイページ</a>
            {% else %}
            <a id="signup" href="{% url 'accounts:signup_and_login' %}">会員登録/ログイン</a>
            {% endif %}
        </div>
    </nav>

    <div class="background">
        <div class="slide slide1"></div>
        <div class="slide slide2"></div>
        <div class="slide slide3"></div>
    </div>
    <!-- メインコンテンツ -->
    <div class="container mx-auto text-center">
        {% block content %}
        {% endblock %}
    </div>
</body>
    <link rel="stylesheet" href="{% static 'css/base2.css' %}{% if style_css_date %}?={{ style_css_date }}{% endif %}">

</html>